/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/questions/{questionUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestion"];
        put: operations["updateQuestion"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-groups/{questionGroupUuid}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateQuestionGroupItems"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{examUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExam"];
        put: operations["updateExam"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/exams/{examUuid}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/attempts/{attemptUuid}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/attempts/{attemptUuid}/proctoring-events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/attempts/{attemptUuid}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["saveAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestions"];
        put?: never;
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestionGroups"];
        put?: never;
        post: operations["createQuestionGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omr/scoring-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createScoringJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omr/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importOmrData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omr/exam-papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createExamPaper"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExams"];
        put?: never;
        post: operations["createExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{questionUuid}/activation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateQuestionActivation"];
        trace?: never;
    };
    "/api/v1/exams/{examUuid}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateExamStatus"];
        trace?: never;
    };
    "/api/v1/student/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/attempts/{attemptUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/attempts/{attemptUuid}/proctoring-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-groups/{questionGroupUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestionGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omr/scoring-jobs/{jobUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScoringJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omr/exams/{examUuid}/exam-papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamPapersByExamUuid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omr/exams/{examUuid}/exam-papers/{paperCode}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadExamPaper"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/exams/{examUuid}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/exams/{examUuid}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/exams/{examUuid}/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReqQuestionAnswerKeyDTO: {
            correctAnswerRaw: string;
        };
        ReqQuestionMcOptionDTO: {
            optionKey: string;
            optionContent: string;
        };
        ReqQuestionTrueFalseStatementDTO: {
            /** Format: int32 */
            statementOrder: number;
            statementContent: string;
        };
        ReqUpdateQuestionDTO: {
            /** Format: int64 */
            gradeId: number;
            questionContent: string;
            imagePath?: string;
            questionTopic?: string;
            /** @enum {string} */
            questionType: "MCQ" | "TFQ" | "SAQ";
            isActive?: boolean;
            mcOptions?: components["schemas"]["ReqQuestionMcOptionDTO"][];
            tfStatements?: components["schemas"]["ReqQuestionTrueFalseStatementDTO"][];
            answerKey: components["schemas"]["ReqQuestionAnswerKeyDTO"];
        };
        ResQuestionDTO: {
            /** Format: uuid */
            questionUuid?: string;
            /** Format: int64 */
            gradeId?: number;
            questionContent?: string;
            imagePath?: string;
            questionTopic?: string;
            /** @enum {string} */
            questionType?: "MCQ" | "TFQ" | "SAQ";
            /** Format: uuid */
            createdByUserUuid?: string;
            isActive?: boolean;
            correctAnswerRaw?: string;
            normalizedAnswer?: string;
            mcOptions?: components["schemas"]["ResQuestionMcOptionDTO"][];
            tfStatements?: components["schemas"]["ResQuestionTrueFalseStatementDTO"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: string;
            updatedBy?: string;
        };
        ResQuestionMcOptionDTO: {
            /** Format: uuid */
            optionUuid?: string;
            optionKey?: string;
            optionContent?: string;
        };
        ResQuestionTrueFalseStatementDTO: {
            /** Format: uuid */
            statementUuid?: string;
            /** Format: int32 */
            statementOrder?: number;
            statementContent?: string;
        };
        ReqQuestionGroupItemDTO: {
            /** Format: uuid */
            questionUuid: string;
        };
        ReqUpdateQuestionGroupItemsDTO: {
            items: components["schemas"]["ReqQuestionGroupItemDTO"][];
        };
        ResQuestionGroupDTO: {
            /** Format: uuid */
            questionGroupUuid?: string;
            groupName?: string;
            /** @enum {string} */
            questionType?: "MCQ" | "TFQ" | "SAQ";
            questionTopic?: string;
            /** Format: int32 */
            questionCount?: number;
            /** Format: uuid */
            createdByUserUuid?: string;
            items?: components["schemas"]["ResQuestionGroupItemDTO"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: string;
            updatedBy?: string;
        };
        ResQuestionGroupItemDTO: {
            /** Format: uuid */
            questionGroupItemUuid?: string;
            /** Format: uuid */
            questionUuid?: string;
            questionDetail?: components["schemas"]["ResQuestionGroupQuestionDetailDTO"];
        };
        ResQuestionGroupQuestionDetailDTO: {
            /** Format: uuid */
            questionUuid?: string;
            questionContent?: string;
            imagePath?: string;
            questionTopic?: string;
            /** @enum {string} */
            questionType?: "MCQ" | "TFQ" | "SAQ";
        };
        ReqCreateQuestionGroupDTO: {
            groupName: string;
            /** @enum {string} */
            questionType: "MCQ" | "TFQ" | "SAQ";
            questionTopic?: string;
            /** Format: int32 */
            questionCount: number;
            items: components["schemas"]["ReqQuestionGroupItemDTO"][];
        };
        ReqExamQuestionDTO: {
            /** Format: uuid */
            questionUuid: string;
            /** Format: int32 */
            questionOrder: number;
            score: number;
            /** @enum {string} */
            sectionType: "MCQ" | "TFQ" | "SAQ";
            /** @enum {string} */
            sourceType: "MANUAL" | "QUESTION_BANK" | "IMPORTED";
        };
        ReqExamQuestionGroupDTO: {
            /** Format: uuid */
            questionGroupUuid?: string;
            newQuestionGroup?: components["schemas"]["ReqCreateQuestionGroupDTO"];
            /** Format: int32 */
            pickQuestionCount: number;
            scorePerQuestion: number;
            /** Format: int32 */
            displayOrder: number;
        };
        ReqUpdateExamDTO: {
            examName: string;
            /** Format: int64 */
            gradeId: number;
            schoolYear: string;
            /** @enum {string} */
            examType: "QUIZ" | "HOMEWORK" | "MOCK_TEST" | "OFFICIAL_TEST";
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** Format: int32 */
            durationMinutes: number;
            totalScore: number;
            /** Format: int32 */
            numberOfAttempt: number;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CLOSED" | "ARCHIVED";
            tfCorrect1Pct?: number;
            tfCorrect2Pct?: number;
            tfCorrect3Pct?: number;
            tfCorrect4Pct?: number;
            examQuestions?: components["schemas"]["ReqExamQuestionDTO"][];
            examQuestionGroups?: components["schemas"]["ReqExamQuestionGroupDTO"][];
        };
        ResExamDTO: {
            /** Format: uuid */
            examUuid?: string;
            examName?: string;
            /** Format: int64 */
            gradeId?: number;
            schoolYear?: string;
            /** @enum {string} */
            examType?: "QUIZ" | "HOMEWORK" | "MOCK_TEST" | "OFFICIAL_TEST";
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** Format: int32 */
            durationMinutes?: number;
            totalScore?: number;
            /** Format: int32 */
            numberOfAttempt?: number;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED" | "CLOSED" | "ARCHIVED";
            /** Format: uuid */
            createdByUserUuid?: string;
            tfCorrect1Pct?: number;
            tfCorrect2Pct?: number;
            tfCorrect3Pct?: number;
            tfCorrect4Pct?: number;
            questionSummary?: components["schemas"]["ResExamQuestionSummaryDTO"];
            questionSections?: components["schemas"]["ResExamQuestionTypeSectionDTO"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: string;
            updatedBy?: string;
        };
        ResExamQuestionDetailDTO: {
            /** Format: uuid */
            questionUuid?: string;
            questionContent?: string;
            imagePath?: string;
            questionTopic?: string;
            /** @enum {string} */
            questionType?: "MCQ" | "TFQ" | "SAQ";
        };
        ResExamQuestionGroupDTO: {
            /** Format: uuid */
            eqgUuid?: string;
            /** Format: uuid */
            questionGroupUuid?: string;
            groupName?: string;
            /** @enum {string} */
            questionType?: "MCQ" | "TFQ" | "SAQ";
            questionTopic?: string;
            /** Format: int32 */
            poolQuestionCount?: number;
            /** Format: int32 */
            pickQuestionCount?: number;
            scorePerQuestion?: number;
            /** Format: int32 */
            displayOrder?: number;
            items?: components["schemas"]["ResExamQuestionGroupItemDTO"][];
        };
        ResExamQuestionGroupItemDTO: {
            /** Format: uuid */
            eqgiUuid?: string;
            /** Format: uuid */
            questionUuid?: string;
            questionDetail?: components["schemas"]["ResExamQuestionDetailDTO"];
        };
        ResExamQuestionSummaryDTO: {
            /** Format: int32 */
            mcqCount?: number;
            /** Format: int32 */
            tfqCount?: number;
            /** Format: int32 */
            saqCount?: number;
        };
        ResExamQuestionTypeSectionDTO: {
            /** @enum {string} */
            questionType?: "MCQ" | "TFQ" | "SAQ";
            /** Format: int32 */
            totalQuestionCount?: number;
            standaloneQuestions?: components["schemas"]["ResExamStandaloneQuestionDTO"][];
            groups?: components["schemas"]["ResExamQuestionGroupDTO"][];
        };
        ResExamStandaloneQuestionDTO: {
            /** Format: uuid */
            examQuestionUuid?: string;
            /** Format: uuid */
            questionUuid?: string;
            /** Format: int32 */
            questionOrder?: number;
            score?: number;
            /** @enum {string} */
            sectionType?: "MCQ" | "TFQ" | "SAQ";
            /** @enum {string} */
            sourceType?: "MANUAL" | "QUESTION_BANK" | "IMPORTED";
            questionDetail?: components["schemas"]["ResExamQuestionDetailDTO"];
        };
        ResAttemptQuestionDTO: {
            /** Format: int32 */
            questionOrder?: number;
            /** Format: uuid */
            questionUuid?: string;
            /** @enum {string} */
            questionType?: "MCQ" | "TFQ" | "SAQ";
            questionContent?: string;
            imagePath?: string;
            questionTopic?: string;
            score?: number;
            fromQuestionGroup?: boolean;
            /** Format: uuid */
            groupUuid?: string;
            groupName?: string;
            mcOptions?: components["schemas"]["ResAttemptQuestionMcOptionDTO"][];
            tfStatements?: components["schemas"]["ResAttemptQuestionTrueFalseStatementDTO"][];
            currentRawAnswer?: string;
            currentNormalizedAnswer?: string;
            /** Format: int32 */
            answerChangeCount?: number;
            correctAnswerRaw?: string;
            correctNormalizedAnswer?: string;
            earnedScore?: number;
        };
        ResAttemptQuestionMcOptionDTO: {
            /** Format: uuid */
            optionUuid?: string;
            optionKey?: string;
            optionContent?: string;
        };
        ResAttemptQuestionTrueFalseStatementDTO: {
            /** Format: uuid */
            statementUuid?: string;
            /** Format: int32 */
            statementOrder?: number;
            statementContent?: string;
        };
        ResExamAttemptDTO: {
            /** Format: uuid */
            attemptUuid?: string;
            /** Format: uuid */
            examUuid?: string;
            examName?: string;
            /** Format: uuid */
            studentUuid?: string;
            studentId?: string;
            studentFullname?: string;
            /** Format: int32 */
            attemptNo?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: int32 */
            timeSpentSeconds?: number;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "SUBMITTED" | "SCORED" | "ANSWER_RELEASED" | "CANCELLED";
            score?: number;
            isAutoSubmitted?: boolean;
            /** Format: int32 */
            violationCount?: number;
            rawImageUrl?: string;
            scoredImageUrl?: string;
            questions?: components["schemas"]["ResAttemptQuestionDTO"][];
        };
        JsonNode: unknown;
        ReqProctoringEventBatchDTO: {
            events: components["schemas"]["ReqProctoringEventDTO"][];
        };
        ReqProctoringEventDTO: {
            /** Format: date-time */
            eventTime?: string;
            /** @enum {string} */
            eventType: "TAB_SWITCH" | "FULLSCREEN_EXIT" | "WINDOW_BLUR" | "COPY_PASTE" | "NETWORK_LOST";
            eventPayload?: components["schemas"]["JsonNode"];
        };
        ResProctoringEventBatchDTO: {
            /** Format: uuid */
            attemptUuid?: string;
            /** Format: int32 */
            acceptedCount?: number;
            events?: components["schemas"]["ResProctoringEventDTO"][];
        };
        ResProctoringEventDTO: {
            /** Format: uuid */
            eventUuid?: string;
            /** Format: uuid */
            attemptUuid?: string;
            /** Format: date-time */
            eventTime?: string;
            /** @enum {string} */
            eventType?: "TAB_SWITCH" | "FULLSCREEN_EXIT" | "WINDOW_BLUR" | "COPY_PASTE" | "NETWORK_LOST";
            eventPayload?: string;
        };
        ReqStudentAnswerDTO: {
            /** Format: uuid */
            questionUuid: string;
            rawAnswer?: string;
        };
        ReqCreateQuestionDTO: {
            /** Format: int64 */
            gradeId: number;
            questionContent: string;
            imagePath?: string;
            questionTopic?: string;
            /** @enum {string} */
            questionType: "MCQ" | "TFQ" | "SAQ";
            isActive?: boolean;
            mcOptions?: components["schemas"]["ReqQuestionMcOptionDTO"][];
            tfStatements?: components["schemas"]["ReqQuestionTrueFalseStatementDTO"][];
            answerKey: components["schemas"]["ReqQuestionAnswerKeyDTO"];
        };
        ResOmrScoringJobDTO: {
            /** Format: uuid */
            jobUuid?: string;
            /** Format: uuid */
            examUuid?: string;
            schoolYear?: string;
            /** @enum {string} */
            status?: "PENDING" | "PROCESSING" | "EXTRACTED" | "IMPORTING" | "COMPLETED" | "FAILED";
            /** Format: int32 */
            pageCount?: number;
            rawImageUrl?: string;
            scoredImageUrl?: string;
            /** Format: int64 */
            resultCount?: number;
            /** Format: int64 */
            completedCount?: number;
            /** Format: int64 */
            failedCount?: number;
            results?: components["schemas"]["ResOmrScoringJobResultDTO"][];
            errorMessage?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ResOmrScoringJobResultDTO: {
            /** Format: uuid */
            jobResultUuid?: string;
            /** Format: int32 */
            pageNumber?: number;
            paperCode?: string;
            studentCode?: string;
            schoolYear?: string;
            studentFullname?: string;
            /** Format: uuid */
            studentUuid?: string;
            /** Format: uuid */
            attemptUuid?: string;
            /** @enum {string} */
            status?: "EXTRACTED" | "IMPORTING" | "COMPLETED" | "FAILED";
            score?: number;
            rawImageUrl?: string;
            scoredImageUrl?: string;
            errorMessage?: string;
        };
        ReqOmrAnswerDTO: {
            /** Format: int32 */
            sectionQuestionNumber: number;
            rawAnswer?: string;
        };
        ReqOmrImportDTO: {
            /** Format: uuid */
            examUuid: string;
            paperCode: string;
            /** Format: uuid */
            studentUuid: string;
            studentId?: string;
            studentFullname?: string;
            externalSubmissionId?: string;
            rawImageUrl?: string;
            scoredImageUrl?: string;
            /** Format: date-time */
            scannedAt?: string;
            sections: components["schemas"]["ReqOmrSectionsDTO"];
        };
        ReqOmrSectionsDTO: {
            mcq?: components["schemas"]["ReqOmrAnswerDTO"][];
            tfq?: components["schemas"]["ReqOmrAnswerDTO"][];
            saq?: components["schemas"]["ReqOmrAnswerDTO"][];
        };
        ResOmrImportDTO: {
            /** Format: uuid */
            omrImportUuid?: string;
            /** Format: uuid */
            examUuid?: string;
            /** Format: uuid */
            paperUuid?: string;
            paperCode?: string;
            /** Format: uuid */
            studentUuid?: string;
            /** Format: uuid */
            attemptUuid?: string;
            externalSubmissionId?: string;
            status?: string;
            score?: number;
            /** Format: date-time */
            importedAt?: string;
        };
        ReqCreateExamPaperDTO: {
            /** Format: uuid */
            examUuid: string;
            paperCode: string;
        };
        ResExamPaperDTO: {
            /** Format: uuid */
            paperUuid?: string;
            /** Format: uuid */
            examUuid?: string;
            paperCode?: string;
            /** Format: date-time */
            generatedAt?: string;
            /** Format: uuid */
            generatedByUserUuid?: string;
            pdfUrl?: string;
            questions?: components["schemas"]["ResExamPaperQuestionDTO"][];
        };
        ResExamPaperQuestionDTO: {
            /** Format: int32 */
            questionOrder?: number;
            /** Format: int32 */
            sectionQuestionNumber?: number;
            /** Format: uuid */
            questionUuid?: string;
            /** @enum {string} */
            questionType?: "MCQ" | "TFQ" | "SAQ";
            imagePath?: string;
            score?: number;
            fromQuestionGroup?: boolean;
            /** Format: uuid */
            groupUuid?: string;
            groupName?: string;
        };
        UploadFileResDTO: {
            fileName?: string;
            /** Format: date-time */
            uploadedAt?: string;
        };
        ReqCreateExamDTO: {
            examName: string;
            /** Format: int64 */
            gradeId: number;
            schoolYear: string;
            /** @enum {string} */
            examType: "QUIZ" | "HOMEWORK" | "MOCK_TEST" | "OFFICIAL_TEST";
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** Format: int32 */
            durationMinutes: number;
            totalScore: number;
            /** Format: int32 */
            numberOfAttempt: number;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CLOSED" | "ARCHIVED";
            tfCorrect1Pct?: number;
            tfCorrect2Pct?: number;
            tfCorrect3Pct?: number;
            tfCorrect4Pct?: number;
            examQuestions?: components["schemas"]["ReqExamQuestionDTO"][];
            examQuestionGroups?: components["schemas"]["ReqExamQuestionGroupDTO"][];
        };
        ReqQuestionActivationDTO: {
            isActive: boolean;
        };
        ReqExamStatusDTO: {
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "CLOSED" | "ARCHIVED";
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageResExamAttemptSummaryDTO: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ResExamAttemptSummaryDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            paged?: boolean;
        };
        ResExamAttemptSummaryDTO: {
            /** Format: uuid */
            attemptUuid?: string;
            /** Format: uuid */
            examUuid?: string;
            examName?: string;
            studentId?: string;
            studentFullname?: string;
            /** Format: int32 */
            attemptNo?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: int32 */
            timeSpentSeconds?: number;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "SUBMITTED" | "SCORED" | "ANSWER_RELEASED" | "CANCELLED";
            score?: number;
            isAutoSubmitted?: boolean;
            /** Format: int32 */
            violationCount?: number;
            rawImageUrl?: string;
            scoredImageUrl?: string;
        };
        SortObject: {
            empty?: boolean;
            unsorted?: boolean;
            sorted?: boolean;
        };
        PageResQuestionDTO: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ResQuestionDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageResQuestionGroupDTO: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ResQuestionGroupDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageResExamDTO: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ResExamDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResQuestionDTO"];
                };
            };
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqUpdateQuestionDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResQuestionDTO"];
                };
            };
        };
    };
    updateQuestionGroupItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionGroupUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqUpdateQuestionGroupItemsDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResQuestionGroupDTO"];
                };
            };
        };
    };
    getExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamDTO"];
                };
            };
        };
    };
    updateExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqUpdateExamDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamDTO"];
                };
            };
        };
    };
    startAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamAttemptDTO"];
                };
            };
        };
    };
    submitAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamAttemptDTO"];
                };
            };
        };
    };
    createEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqProctoringEventBatchDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResProctoringEventBatchDTO"];
                };
            };
        };
    };
    saveAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqStudentAnswerDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamAttemptDTO"];
                };
            };
        };
    };
    getQuestions: {
        parameters: {
            query: {
                gradeId?: number;
                topic?: string;
                content?: string;
                type?: string;
                isActive?: boolean;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResQuestionDTO"];
                };
            };
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqCreateQuestionDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResQuestionDTO"];
                };
            };
        };
    };
    getQuestionGroups: {
        parameters: {
            query: {
                name?: string;
                type?: string;
                topic?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResQuestionGroupDTO"];
                };
            };
        };
    };
    createQuestionGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqCreateQuestionGroupDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResQuestionGroupDTO"];
                };
            };
        };
    };
    createScoringJob: {
        parameters: {
            query: {
                examUuid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResOmrScoringJobDTO"];
                };
            };
        };
    };
    importOmrData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqOmrImportDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResOmrImportDTO"];
                };
            };
        };
    };
    createExamPaper: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqCreateExamPaperDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamPaperDTO"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query: {
                folder: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UploadFileResDTO"];
                };
            };
        };
    };
    getExams: {
        parameters: {
            query: {
                gradeId?: number;
                name?: string;
                type?: string;
                status?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResExamDTO"];
                };
            };
        };
    };
    createExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqCreateExamDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamDTO"];
                };
            };
        };
    };
    updateQuestionActivation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqQuestionActivationDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResQuestionDTO"];
                };
            };
        };
    };
    updateExamStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReqExamStatusDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamDTO"];
                };
            };
        };
    };
    getAttempts: {
        parameters: {
            query: {
                examUuid?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResExamAttemptSummaryDTO"];
                };
            };
        };
    };
    getAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamAttemptDTO"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResProctoringEventDTO"][];
                };
            };
        };
    };
    getQuestionGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionGroupUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResQuestionGroupDTO"];
                };
            };
        };
    };
    getScoringJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResOmrScoringJobDTO"];
                };
            };
        };
    };
    getExamPapersByExamUuid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResExamPaperDTO"][];
                };
            };
        };
    };
    downloadExamPaper: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examUuid: string;
                paperCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getExamStats: {
        parameters: {
            query?: {
                exportXlsx?: boolean;
            };
            header?: never;
            path: {
                examUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getExamResults: {
        parameters: {
            query?: {
                exportXlsx?: boolean;
            };
            header?: never;
            path: {
                examUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getExamRanking: {
        parameters: {
            query?: {
                n?: number;
                exportXlsx?: boolean;
            };
            header?: never;
            path: {
                examUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
}
