export const paths = {
  home: '/',
  courses: '/courses',
  courseDetail: (gradeId: string | number, lessonTypeId: string) => `/courses/${gradeId}/${lessonTypeId}`,
  schedule: '/schedule',
  exam: '/exam',
  adminPortal: '/admin-portal',
  adminPortalOverview: '/admin-portal/overview',
  adminPortalRegistrations: '/admin-portal/registrations',
  adminPortalClasses: '/admin-portal/classes',
  adminPortalClassDetail: (userUuid: string) => `/admin-portal/classes/${userUuid}`,
  adminPortalUsers: '/admin-portal/users',
  adminPortalPeriodSettings: '/admin-portal/period-settings',
  adminPortalTimetable: '/admin-portal/timetable',
  adminPortalTimetableAll: '/admin-portal/timetable/all',
  adminPortalTimetableGrade: (gradeId: string | number) => `/admin-portal/timetable/grade/${gradeId}`,
  adminPortalStudyWeeks: '/admin-portal/study-weeks',
  adminPortalStudyWeekDetail: (weekUuid: string) => `/admin-portal/study-weeks/${weekUuid}`,
  adminPortalStudyWeekByGrade: (weekUuid: string, gradeId: string | number) =>
    `/admin-portal/study-weeks/${weekUuid}/grade/${gradeId}`,
  adminPortalStudyWeekLesson: (weekUuid: string, gradeId: string | number, lessonUuid: string) =>
    `/admin-portal/study-weeks/${weekUuid}/grade/${gradeId}/lessons/${lessonUuid}`,
  adminPortalLearningResources: '/admin-portal/learning-resources',
  adminPortalCosts: '/admin-portal/costs',
  adminPortalExamQuestions: '/admin-portal/exam/questions',
  adminPortalExams: '/admin-portal/exam/exams',
  login: '/',
} as const;
